name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensures all submodules, including nested, are initialized

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            libeigen3-dev \
            libglfw3-dev \
            libzip-dev \
            libboost-dev \
            libx11-dev \
            libomp-dev \
            libsdl2-dev \
            libassimp-dev \
            libmagnum-dev \
            libcorrade-dev

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: build
        run: cmake -DBUILD_NIX_PACKAGE=OFF ..

      - name: Build with Make
        working-directory: build
        run: make -j

      - name: Verify build
        run: |
          if [ ! -f build/Release/bin/CLIContactSimulation ]; then
            echo "Build failed: CLIContactSimulation not found"
            exit 1
          fi
        shell: bash
