name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/primal-dual-simulation:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/primal-dual-simulation:latest

      - name: Run Docker Container
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/primal-dual-simulation:latest
